name: update
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  run_bash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@main
        
      - name: Run the script
        run: bash ./cron/ip.sh
        
      - name: Commit
        id: commit
        run: |
          git config --global user.name '1054009064'
          git config --global user.email '44148148+1054009064@users.noreply.github.com'
          if [[ $(git status) == *"nothing to commit"* ]]; then
            echo "Nothing to commit, working tree clean."
          else
            git add .
            git commit -m "Automatic update"
            echo "DATE=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV # ${{ env.DATE }}
            echo "status=successful" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.status == 'successful'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: false

      - name: Process the zip folder
        run: |
          mkdir -p zip
          zip -qj9 ./zip/wireguard.zip ./wireguard/*
          zip -qj9 ./zip/openvpn.zip ./openvpn/*
          cd zip
          echo "sha256sums:" >> zip.sha256sums
          echo "\`\`\`" >> zip.sha256sums
          sha256sum *.zip >> zip.sha256sums
          echo "\`\`\`" >> zip.sha256sums
          echo "ZIP=$PWD" >> $GITHUB_ENV

      - name: Upload zip directory
        uses: actions/upload-artifact@main
        with:
          name: ZIP
          path: ${{ env.ZIP }}

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        if: steps.commit.outputs.status == 'successful' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.DATE }}
          body_path: ${{ env.ZIP }}/zip.sha256sums
          files: ${{ env.ZIP }}/*.zip

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 7
